/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    FeaturePage: typeof import('./src/components/FeaturePage.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    InformationPage: typeof import('./src/components/InformationPage.vue')['default']
    PricePage: typeof import('./src/components/PricePage.vue')['default']
    ProfilePage: typeof import('./src/components/ProfilePage.vue')['default']
    StoryPage: typeof import('./src/components/StoryPage.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
